### ISSUE TITLE
make `newlisp-complete-symbol` support `completion-at-point-functions` and company-mode etc

### ISSUE THREAD

**Issue by stardiviner** [kosh04/newlisp-mode#7]
I try to add `newlisp-complete-symbol` to `completion-at-point-functions` to make it can used by `company-mode`.
But it still popup candidates in `*Completions*` buffer.
`completion-at-point-functions` is Emacs standard completion interface.

**Comment by kosh04** [comment]
@stardiviner Since v.0.3.3, completion function is compatible with `company-mode`.

Please update MELPA package and try it.
